
version: '3'

services:
  web:
    build: .
    volumes:
      - .:/web_auth
    ports:
      - '8000:8000'
    depends_on:
      - db
    

  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'auth'
      MYSQL_ROOT_PASSWORD: 'qwerty'
    restart: always
